indexing-settings:
  sites:
    - url: https://dimonvideo.ru/
      name: dv
    - url: https://lenta.ru/
      name: lenta

useragent-settings:
  userAgentApp: Mozilla/5.0 (Windows; U; WindowsNT5.1; en-US; rv1.8.1.6) Gecko/20070725 Firefox/2.0.0.6
  referrer: http://www.google.com

server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/search_engine
    username: root
    password: hgThgj
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true

logging:
  level:
    root: INFO
    org.springframework.jdbc.core.JdbcTemplate: DEBUG